.travis.yml
CONTRIBUTING.md
README.md

Over multiple commits, it's clear that formatting has suffered. This
commit normalizes headers, links to resoruces, and Markdown formatting.
This commit adds type-1 headers for top-level menu links. To better
segment Related Projects, this commit segments related projects into
type-2 headers for Related Software, Monitoring Services, PaaS
Providers, and Continuous Delivery. I found it hard to figure out
where everything fit when I first read, so I hope this helps clear
up the hierarchy of those sections.
No new project links have been added, but some 404 links have been
removed, a failing Travis test has been fixed (slideshare.net links),
and official Kubernetes links have been added to the previously-empty
Main Resources section. I hope this helps.

Clean-Up Markdown Formatting

---

README.md

This commit adds Supergiant to the list of Related Software and a link
to an article on the supergiant.io blog about top reasons businesses
should switch to using Kubernetes right away. I hope this is helpful.

Add Supergiant to list

---

.travis.yml
README.md

This commit fixes the broken Travis tests by whitelisting new linked
domains and debugging a broken Google research link about the Borg
project.

Whitelist and debug new links

---

README.md
SUMMARY.md

Katacoda is a free interactive learning environment for software developers. We recently added a Kubernetes environment and scenarios to help people get started and learn how to run a cluster in production.

Add Katacoda to the list

---

README.md

Hello, Datadog recently released a 3 part kubernetes monitoring guide. It's monitoring tool agnostic and focuses on the key metrics and ways to access them for kubernetes. I thought it would be a good fit here.
Part 1: Monitoring in the Kubernetes era
https://www.datadoghq.com/blog/monitoring-kubernetes-era/
Part 2: Monitoring Kubernetes performance metrics
https://www.datadoghq.com/blog/monitoring-kubernetes-performance-metrics/
Part 3: How to collect and graph Kubernetes metrics
https://www.datadoghq.com/blog/how-to-collect-and-graph-kubernetes-metrics/

Add Kubernetes monitoring guide

---

README.md

I am adding an Enterprise Product category as it is sort of between a
PaaS and just using open source Kubernetes.
The first entry is CoreOS Tectonic which builds on top of pure upstream
Kubernetes and integrates a number of features like self-driving
automated updates, identity, and more.
https://coreos.com/tectonic

README: add CoreOS Tectonic as an enterprise product

---

README.md

The Markdown was not formatted correctly, thus not a clickable link.

Fixing Markdown Error

---

README.md

Updating the README.md file with the Apache 2.0 license information for Juju.

Updating the Juju deployer to Apache-2.0 license.

---

README.md

It is the same reasoning as Tectonic. They provide PaaS and enterprise support.
cc @philips what do you think?

Move openshift to the Enterprise category

---

README.md

Archon is a cloud operator and Kubernetes extension that can be used to not only install Kubernetes, but also scale and provision nodes.
Kube-Aliyun is an out-of-tree cloud provider and controllers for the Biggest cloud in China AliCloud/Aliyun. It provides support for LB, Routes, Volumes and also PV provisioning.
Thanks very much.

Add Archon and Kube-Aliyun

---

README.md

Kubetail - Bash script that enables you to aggregate (tail/follow) logs from multiple pods into one stream. This is the same as running "kubectl logs -f " but for multiple pods.

Added Kubetail under Monitoring

---

README.md

Linen is a network plugin and it respect CNI SPEC to create a overlay network in kubernetes.
Linen CNI is for overlay networks with Open vSwitch. It focuses on  SDN/OpenFlow network and supports for adding SDN controller such as ONOS, Ryu and OpenDaylight by configuring network configuration. Linen CNI follows the document (https://kubernetes.io/docs/admin/ovs-networking/) setup with VxLAN. 
The distinguish between ovs-kubernetes and linen please check https://github.com/John-Lin/linen-cni#should-i-use-this-or-ovn-kubernetes
This is a experimental project and try to reduce manual setup by commands with Open vSwitch.

Add Linen CNI plugin

---

README.md

Hi!
Yesterday, I published kube-prompt.
https://github.com/c-bata/kube-prompt
This is similar with kube-shell (written in python and python-prompt-toolkit).
But, kube-prompt is built with golang and [go-prompt - golang porting of python-prompt-toolkit](https://github.com/c-bata/go-prompt).
So it can generate multi-platform binary.
I hope you like kube-prompt.

Add kube-prompt in API/CLI adaptors

---

README.md

This PR adds Kubernetes' kompose and Justin Garrison's kubeval to the section of YAML/JSON Config. Additionally, it fixes the section's anchor id value (navigating to the section from the ToC was broken).

Add kompose and kubeval to YAML/JSON Config. Fix section's anchor id value.

---

README.md

This pull request adds the documentation to run your kubernetes on-premises cluster with openstack as cloud provider.
Article: https://medium.com/@arthur.souzamiranda/kubernetes-with-openstack-cloud-provider-current-state-and-upcoming-changes-part-1-of-2-48b161ea449a

Add article with the openstack as cloud provider tutorial

---

README.md

For the consistency purpose under section `Managed Kubernetes`, I have updated links for _Platform9_ and _Gravitational_.

Update links for Platform9 and Gravitational under managed k8s

---

README.md

Hong Kong meetups are just getting started, but it warrants an addition to the list already.

Add Hong Kong meetup group

---

README.md

I would like to suggest to include [PowerfulSeal](https://github.com/bloomberg/powerfulseal) in the list:
> __PowerfulSeal__ adds chaos to your Kubernetes clusters, so that you can detect problems in your systems as early as possible. It kills targeted pods and takes VMs up and down.
Full disclosure: I'm the main contributor, and I presented the tool last week at [Kubecon 2017 North America](https://events.linuxfoundation.org/events/kubecon-and-cloudnativecon-north-america/program/schedule)
Tell me what you think :-)

Suggest to include PowerfulSeal in the list

---

README.md

The referenced birthday was the launch of Kubernetes 1.0: http://blog.kubernetes.io/2016/07/happy-k8sbday-1.html

rename GKE, and clarify birthday

---

README.md

the scheduler is not maintained anymore and points simply to k8s CronJob docs

remove kron scheduler since its part of k8s core now

---

README.md

kube-ui has been deprecated and not being developed for past 2 years.

Removing kube-ui

---

README.md

KPM Package manager is deprecated and it is no longer developed. It is made official by CoreOS last year and they have not made any changes for last one year

Removing KPM

---

README.md

* Announced at the Azure/Docker/Kubernetes meetup in Seattle today.
Virtual Kubelet is an open source Kubernetes kubelet implementation that masquerades as a kubelet for the purposes of connecting Kubernetes to other APIs. This allows the nodes to be backed by other services like ACI, Hyper.sh, AWS, Azure, etc. This connector features a pluggable architecture and direct use of Kubernetes primitives, making it much easier to build on.

Add Virtual Kubelet

---

README.md

The Grafana Kubernetes App allows you to monitor your Kubernetes cluster's performance. It includes 4 dashboards, Cluster, Node, Pod/Container and Deployment. It allows for the automatic deployment of the required Prometheus exporters and a default scrape config to use with your in cluster Prometheus deployment. The metrics collected are high-level cluster and node stats as well as lower level pod and container stats. Use the high-level metrics to alert on and the low-level metrics to troubleshoot.

Add Grafana Kubernetes App

---

README.md

Skaffold is a command line tool that facilitates continuous development for Kubernetes applications. You can iterate on your application source code locally then deploy to local or remote Kubernetes clusters. Skaffold handles the workflow for building, pushing and deploying your application. It can also be used in an automated context such as a CI/CD pipeline to leverage the same workflow and tooling when moving applications to production.
Stars: 1800+, Google Cloud Platform tool

Add GCP Skaffold CLI Tool

---

README.md

Gitkube is a tool for building and deploying docker images on Kubernetes using git push.
After a simple initial setup, developers can simply keep git push-ing their repos to build and deploy to Kubernetes automatically.
Ideal for development where you can push your WIP branch to the cluster to test.
977+ stars: Github: https://github.com/hasura/gitkube

Add Gitkube

---

README.md

I added this under the monitoring section, as  I don't think it should be grouped with network plugins. The best place for it is probably a logging section though

add eventrouter

---

README.md

Stern allows you to tail multiple pods on Kubernetes and multiple containers within the pod. Each result is color coded for quicker debugging.
The query is a regular expression so the pod name can easily be filtered and you don't need to specify the exact id (for instance omitting the deployment id). If a pod is deleted it gets removed from tail and if a new is added it automatically gets tailed.
When a pod contains multiple containers Stern can tail all of them too without having to do this manually for each one. Simply specify the container flag to limit what containers to show. By default all containers are listened to.

Add stern log tailer

---

README.md

Theseus is a command-line tool for comparing sets of Kubernetes objects. It reads object definitions from a running cluster, an Ark backup file, or a local directory, and performs a comparison to another source of object definitions. Theseus provides reports of which objects are in the first source only, the second source only, and both. Additionally, for objects that are in both, it performs a line-by-line comparison of the object definitions, which it outputs to stdout with highlighting, and to a text file.

add thesus

---

README.md

Implements a Kubernetes ingress controller using cloudflare-warp tunnel to connect a cloudflare-managed URL to a Kubernetes service.

Add cloudflare warp ingress

---

README.md

Longhorn from Rancher is a PVC provider available as of March 27, 2018
http://rancher.com/project-longhorn-now-available-kubernetes/

Adding Rancher Longhorn to PVC section

---

README.md

I'm opening a new PR since #255 was closed because we didn't meet the criteria at that time.
Hello, please reconsider linking the Awesome Helm list - https://github.com/cdwv/awesome-helm that we're maintaining as a resource of Helm-specific links (documentation, charts, etc.)

Add a link to the Awesome Helm list

---

README.md

Kubernetes 1.11 was [just](https://kubernetes.io/blog/2018/06/27/kubernetes-1.11-release-announcement/) released.

Add release notes for K8s 1.11

---

README.md

Hi, just wanted to resubmit a PR I opened shortly after the criteria guideline was put into place.
Previous PR: #214
Summary:
Adds an entry for kubectl-plugins, under the 'API/CLI adaptors' section. The plugins are simple and address some of the limitations of kubernetes such as kubernetes/kubernetes#30656 (using kubectl exec with a user flag). This was a significant pain to deal with while trying to maintain proper security contexts amongst my k8 containers.
The homepage has animated gifs in the README for quick demos on some plugins.

Add kubectl-plugins to list

---

README.md

The Containerum link pointed to `containerum.io`; this is down, so automated builds are failing due to the link checker. The correct URL appears to be `containerum.com`.

Fix Containerum URL

---

README.md

Added kubefwd. Bulk port forwarding Kubernetes services for local development.
This project now has over 400 stars and is actively growing its contributor base. Kelsey Hightower recently tweeted about it.  https://twitter.com/kelseyhightower/status/1059519420064706579 (hope that makes it awesome!)

Add kubefwd

---

README.md

Great to see Kubeapps on this list :), thanks for adding it @alljames! There was some initial confusion (https://github.com/ramitsurana/awesome-kubernetes/pull/246) on where to place it - now that our project goals are to focus on application deployment and management, I think the Web applications category might be a better home.

Move Kubeapps under Web applications

---

README.md

**_kube-fledged_** is a kubernetes add-on for creating and managing a cache of container images directly on the worker nodes of a kubernetes cluster. It allows a user to define a list of images and onto which worker nodes those images should be cached (i.e. pre-pulled). As a result, application pods start almost instantly, since the images need not be pulled from the registry.
_kube-fledged_ provides CRUD APIs to manage the lifecycle of the image cache, and supports several configurable parameters to customize the functioning as per one's needs.
URL:- https://github.com/senthilrch/kube-fledged
**Note:-** _kube-fledged_ fulfills the [Acceptance Criteria](https://github.com/ramitsurana/awesome-kubernetes/blob/master/guidelines/CRITERIA_OF_SUBMISSION.md)

Add 'kube-fledged' to 'Related Software' section

---

README.md

[Goldpinger](https://github.com/bloomberg/goldpinger) is a new tool for monitoring inter-cluster connectivity, that we just open sourced and [presented at KubeCon 2018 Seattle](https://kccna18.sched.com/event/337fdd277ec50252ed03826670f1e7fe).
Copied from https://github.com/ramitsurana/awesome-kubernetes/pull/350 because it only had 4 contributors last night.

Suggest adding Goldpinger to the list

---

README.md

I believe this project adheres to your guidelines (even if perhaps the stars and contributors metrics miss the mark) on the grounds of it being hosted by a recognized organization (among other things, maintainers of kubecfg)

Add bitnami kube-libsonnet

---

README.md

It is a kubectl plugin by that allows users to schedule [bpftrace](https://github.com/iovisor/bpftrace) programs on kubernetes clusters.
Commands:
- attach
- run
- delete
- log
- get
- trace
- version

Add kubectl-trace plugin

---

README.md

Adds the following services to the Development Platform Section:
- Eclipse Che from Eclipse Foundation/ Red Hat Inc.
- OpenShift.io from Red Hat Inc. - Presumably a Fabric8 hosted solution with Jenkins CI and Eclipse Che tooling. Probably the Fabric8 hosted reference implementation.

Add Eclipse Che and OpenShift.io to DevPlatform

---

README.md

Repo moved to https://github.com/jimmycuadra/ktmpl

Update url of Ktmpl repo

---

README.md

I realize that Argo Workflow Engine is already mentioned in the "Related Software" section but I believe the Argo CD project deserves a dedicated mention in the "Continuous Delivery" section.

Add Argo CD to Continuous Delivery section

---

README.md

This is an article about Kubernetes authentication via GitHub OAuth and Dex.
I think it could be useful here.

Add link to authentication article

---

README.md

Since lately https://github.com/gardener/gardener/pull/626 Gardener now also supports Alibaba Cloud.

Add Alibaba to supported IaaS list for Gardener

---

README.md

The [original pykube](https://github.com/kelproject/pykube/) is unmaintained (git repo is archived) and I'm trying to resurrect and maintain it (already released on PyPI). 
The [new repo](https://github.com/hjacobs/pykube) does not have any stars yet, but I consider this PR an improvement as the current link points to an unmaintained project (from the README: "If you see a package or project here that is no longer maintained or is not a good fit, please submit a pull request to improve this file.").

pykube -> pykube-ng

---

README.md

Fabric8 upstream project is abandoned and redhat's fork of it called openshift.io is not ready for public consumption yet as it's still a private beta. Both do not add any value to this otherwise pretty great list of resources.  
Source: I used to work on these projects at Redhat.

Remove Fabric8 and Openshift.io

---

README.md

Move "Logging in Kubernetes with Fluentd and Elasticsearch" article from Useful Articles/Cloud Providers to Useful Articles/Logging

Move logging article link to correct section

---

README.md

OperatorHub.io was launched by Red Hat in conjunction with Amazon, Microsoft, and Google.

Add OperatorHub.io as a central Kubernetes Operator market place

---

README.md

We recently moved the `kubecfg` component to the `bitnami` organization (due to a reorganization in the `ksonnet` org).
GitHub does the redirect automatically so all existing links work but nevertheless I think it would be better to have the new official link here.
Context/Proof: https://github.com/ksonnet/kubecfg/issues/247#issuecomment-479976130

Update kubecfg location (ksonnet -> bitnami)

---

README.md

Hi! This PR adds a link to [Cloudsmith](https://cloudsmith.io), which is a package management service SaaS. It's commercial, but it is completely free for open-source and it has generous free tiers otherwise. It has first-class support for Kubernetes / Docker + Helm (and many other package formats, such as Npm), plus org/teams management, granular access controls, private repositories, repository-specific entitlements, a worldwide content distribution network, webhooks, access logs, etc. Thank you. :-)
Full disclosure: I work at Cloudsmith. \o/
As a part of our practice, we would like to select the projects based on the below criteria. Please ensure that your submission is …

Added Cloudsmith (Kubernetes Registry)

---

README.md

Added MicroK8s and k3s to "Installers" list.
[MicroK8s](https://github.com/ubuntu/microk8s) - A single package of k8s that installs on 42 flavours of Linux, by Canonical.
[k3s](https://github.com/rancher/k3s) - Lightweight Kubernetes. Easy to install, half the memory, all in a binary less than 40mb, by Rancher.

Add "Installers" projects

---

README.md

https://github.com/VirtusLab/jenkins-operator states that it has moved to https://github.com/jenkinsci/kubernetes-operator

update jenkins operator url

---

README.md

Adds [chaoskube](https://github.com/linki/chaoskube) to the tooling section alongside similar projects like `kube-monkey`. `chaoskube` is a simple tool that periodically kills random pods in a cluster. It allows to filter pods by various means such as labels, annotations, pod name, and livetime of the pod.
Added in alphabetical order. Hope that's ok.

Adds chaoskube

---

README.md

in this context, it appears that the author expected the `Inspired by` part to appear on a new line (when in fact it does not).

typo: markdown doesn't respect line breaks

---

README.md

[kubedash](https://github.com/kubernetes-retired/kubedash) repository is read only and belong to an organization for "kubernetes projects that are no longer actively maintained".
I would say it is safe to remove it from the list.

Remove kubedash

---

README.md

StackPoint Cloud is now NetApp Kubernetes Service (NKS)
It would be better if Managed Kubernetes providers were ordered alphabetically, but I did not change that. I hope a maintainer can edit this PR and make that modification

Rename StackPoint Cloud to NKS

---

README.md

one link is dead but unrelated to this PR.
```
Issues :-(
> Links
1. [L0337] 403 http://www.sdxcentral.com/articles/news/why-docker-and-google-kubernetes-are-like-paas-done-right/2015/08/
```

Add https://github.com/k14s/ytt to Configuration section

---

README.md

5  contributors. 288 starts. Okteto lets you develop directly in any Kubernetes cluster. No commit, build or push required.

Add Okteto link

---

README.md

The link to CrateDB's Kubernetes documentation was outdated.

Update link to CrateDB Kubernetes documentation

---

README.md

Add Kubernetes Resource Report which can generate a HTML report of CPU/memory requests vs. usage (collected via Metrics API/Heapster) for one or more Kubernetes clusters.
Live demo is available on https://demo.j-serv.de/
Criteria is matched:
* project has 292 GitHub stars
* project has 15 contributors

Kubernetes Resource Report

---

README.md

Z.A.R.V.I.S. is a Paas platform that deploys Github projects on managed Kubernetes with free tier option with optional extra quota for open source project.

Add zarvis.ai to Paas platform list

---

README.md

Link new project Kubernetes Web View:
> Kubernetes Web View allows to list and view all Kubernetes resources (incl. CRDs) with permalink-friendly URLs in a plain-HTML frontend. This tool was mainly developed to provide a web-version of kubectl for troubleshooting and supporting colleagues.
See introductory blog post on https://srcco.de/posts/kubernetes-web-uis-in-2019.html
- Minimum of 25 GitHub Stars: yes, mirror on https://github.com/hjacobs/kube-web-view has 32 stars plus 9 stars on https://codeberg.org/hjacobs/kube-web-view
- Minimum of 3+ contributors: no, only two contributors so far
- Proper documentation of the project and its goals: yes, see https://kube-web-view.readthedocs.io/en/latest/ and https://srcco.de/posts/kubernetes-web-uis-in-2019.html

Kubernetes Web View

---

README.md

eksctl allows you to provision and manage EKS clusters on AWS.

Add eksctl to the list of installers

---

README.md

Werf is currently a GitOps delivery tool.
Werf documentation is at https://werf.io

Updated Werf GitOps tool description and URL

---

README.md

It looks like the old spelling might have been French.  Corrected (both English and Americ use 'agnostic').

Correct spelling of 'agnostic'

---

README.md

Adding https://github.com/inovex/illuminatio to the list of the network tooling in Kubernetes. 
TLDR: `illuminatio is a tool for automatically testing kubernetes network policies.`

Add illuminatio in the networking section

---

README.md

Shopify renamed their tool to krane.

 upstream renamed from kubernetes-deploy to krane

---

README.md

Removing plugins got stale (not updated since 6 months)
and/or do not have a high relevance. The Kubernetes CSI
documentation lists all plugins, there is no need
to list them in a featured list.
Added some new projects raised in the last few months.

Update CSI plugins

---

README.md

Octopus is a testing framework that allows you to run integration tests defined as Docker images on a Kubernetes cluster.
It can be replacement for a `helm test`.
Here you can find a blog post that explains why we decided to write this tool and what are the main advantages: https://medium.com/@kymaopensource/how-we-approached-integration-testing-in-kubernetes-and-why-we-stopped-using-helm-tests-e2d3609e6ed9

Add Octopus testing framework

---

README.md

Adding a project to related software projects which helps track versions and vulnerabilities in the Kubernetes world.

Adding k8s-platform-lcm to related software projects

---

README.md

Spring Cloud Kubernetes has moved to a new repo. Also, the correct name for the project appears to be Spring Cloud Kubernetes, not Spring Cloud integration.

Spring Cloud Kubernetes has moved

---

README.md

Adding k8s-label-rules-webhook since I haven't seen another application like it available in the kubernetes world.
[k8s-label-rules-webhook documentation](https://github.com/circa10a/k8s-label-rules-webhook)

add k8s-label-rules-webhook

---

README.md

Remove WSO2 from PaaS Section, because WSO2 is not PaaS and not usage k8s, wso2 is a integrator and api manager.

Remove WSO2 from PaaS Section

---

README.md

Hi,
Great project,
I wanted to suggest you to add couple of things:
In the security section of tool projects:
https://github.com/ramitsurana/awesome-kubernetes#security-1
Add:
kubiscan - A tool to scan Kubernetes cluster for risky pods and RBAC permissions
kubeletct - A client for kubelet and finding vulnerable pods by kubelet
In the security section for articles:
https://github.com/ramitsurana/awesome-kubernetes#security
Add:
Securing Kubernetes Clusters by Eliminating Risky Permissions - by Eviatar Gerzi
Eight Ways to Create a Pod - by Eviatar Gerzi
In the security section of other useful videos:
https://github.com/ramitsurana/awesome-kubernetes#other-useful-videos
Add:
Compromising Kubernetes Cluster by Exploiting RBAC Permissions by Eviatar Gerzi

Add RBAC articles, kubiscan and kubeletctl

---

README.md

PlanetSCaleDB on HN: https://news.ycombinator.com/item?id=20085035
Both PlanetScaleDB Operator and Vitess Operators have been released by the team also working on Vitess (already on the list).

Add PlanetScaleDB Database, Vitess and PlanetScale Operators

---

README.md

This commit adds [Classpert](https://classpert.com/kubernetes) to the section MOOCS/Courses, with a comprehensive selection of 65 Kubernetes courses (free and paid) from providers like Udemy, Pluralsight, Coursera and Skillshare.

Add Classpert courses to MOOCs section

---

README.md

Rkt has no relevance anymore. CoreOS doesn't exist anymore and
Red Hat does support the CRI-O container runtime.
The rkt github project has been archived [1].
[1] https://github.com/rkt/rkt/

Remove container runtime rkt

---

README.md

Red Hat has taken over CoreOS and the mentioned projects have been
moved to other organisations.
CoreOS is used by OpenShift and the only public version is based on
Fedora now.
CoreOS itself has no added value anymore on Twitter.

Update CoreOS links

---

README.md

I believe Krucible meets the relevant criteria. I've added it to both the installers and testing sections because kind is in both and I think Krucible solves the same set of problems (though kind is self-hosted and Krucible is a managed service).

Add Krucible

---

README.md

This is the update for #600 
Sorry I let that go stale. I had made the change but think I forgot to push it to the branch. The cert is only for www. So this last commit switches to http and the redirect takes care of adding www to the hostname.

Add Bottlerocket and cnibook

---

README.md

Add VMware Tanzu Kubernetes Grid to the the Enterprise products : Project is hosted by a recognized organization.
Add Antrea to Networking : Github project has > 600 stars and 26 contributors
-

Add VMware Tanzu Kubernetes Grid 

---

README.md

kube-eventer is similar with <a href="https://github.com/heptiolabs/eventrouter">eventrouter</a> but more powerful. Here are some basic information.
- 288 GitHub Stars
- 13 contributors
- document for 11 sinks 
- release v1.0.0 v1.1.0 v1.2.0 and prepare for release v1.3.0

add kube-eventer to awesome-kubernetes

---

docs/projects/projects.md

This PR adds [kconf](https://github.com/particledecay/kconf), a command line tool for managing multiple Kubernetes configs easily and in one place. Feature highlights:
- No more need for setting `KUBECONFIG`
- No need to copy configs anywhere
- Add and remove configs with one command
- Quickly switch contexts in any config
- Set default namespace
- Export configs
- Autocomplete in Bash, ZSH, and Fish shells

docs: add kconf to CLI tool section

---

docs/managed-kubernetes/managed-kubernetes.md

I'd like to see If I can add staroid.com to PaaS section of managed kubernetes.

Add staroid.com to PaaS section of managed kubernetes

---

docs/projects/projects.md

Since [Mirantis acquired Kontena](https://containerjournal.com/topics/container-management/mirantis-acquires-open-source-lens-ide-project/).
Kontena is not mentionned anymore.
Hope this help to make this awesome list more accurate.
Thanks !

update lens url and title

---

docs/projects/projects.md

I'd like to add [KubeLibrary](https://github.com/devopsspiral/KubeLibrary) to testing section of projects .

add KubeLibrary to projects

---

docs/learning-resources/books.md

The blog link for "Cloud Native Devops with Kubernetes" is broken, so It should be removed

Remove broken blog link

---

docs/projects/projects.md

PureLB is an open-source load-balancer orchestrator for Kubernetes
clusters. It uses standard Linux networking and routing protocols, and
works with the operating system to announce service addresses.

Add the PureLB load balancer orchestrator

---

docs/README.md

This commit fixes the dead link of ci status in README.md.
currently the badge of ci status not appears, because
https://semaphoreci.com/ramitsurana/awesome-kubernetes is not valid.

Fix deadlink of ci status in README to github action links validator

---

docs/installers/installers.md

Harvester is an open-source hyper-converged infrastructure (HCI) software built on Kubernetes. It is an open alternative to using a proprietary HCI stack that incorporates the design and ethos of Cloud Native. Includes Longhorn, KubeVirt, built on top of K3OS.
Requirements for any project submissions
- Minimum of 25 GitHub Stars: Yes
- Minimum of 3+ contributors: Yes
- Proper documentation of the project and its goals: Yes, see Harvester Docs.
Exceptions
Project is hosted by a recognized organization. …

Added Harvester HCI to installers page.

---

docs/projects/projects.md

Hello,
Capact is a new framework for managing applications and infrastructure (day-one and day-two operations). You can learn more about the concept on the website: https://capact.io
All requirements are met:
Hope you like it! Cheers!

Add Capact to related Kubernetes projects

---

docs/projects/projects.md

API traffic viewer for Kubernetes enabling you to view all API communication between microservices, multiprotocol support: HTTP1.1, HTTP/2, AMQP, Kafka, Redis.
Link to Gihub repo:
https://github.com/up9inc/mizu

Adding Mizu to projects/'Monitoring Services'

---

docs/projects/projects.md

[Helmify](https://github.com/arttor/helmify) is a CLI tool to automatically generate Helm charts from K8s manifests.
- Minimum of 25 GitHub Stars - 191 ✅ 
- Minimum of 3+ contributors - 4 ✅ 
- Proper documentation of the project and its goals - ✅

add helmify

---

docs/articles/articles.md

Adds an article on [autoscaling nodes and pods](https://www.useanvil.com/blog/engineering/autoscaling-kubernetes-in-gke/) to the cloud providers section. It seemed like the most relevant section as it describes autoscaling through a GKE lens.

Add autoscaling article to articles page in the cloud providers section

---

docs/articles/articles.md

Adds [Load balancing gRPC in Kubernetes with a service mesh](https://www.useanvil.com/blog/engineering/load-balancing-grpc-in-kubernetes-with-istio) article to the Networking section of the articles page
Open to putting it in another category, let me know! Networking felt like the best fit here.

Add load balancing gRPC article to articles page

---

docs/projects/projects.md

This PR adds mention of [kubernetes-el](https://github.com/kubernetes-el/kubernetes-el), an Emacs client for Kubernetes cluster management with good adoption (500+ stars). It has had substantial contributions over the years. It is also [extensively documented](https://kubernetes-el.github.io/kubernetes-el/).
Disclaimer: I am one of the co-maintainers of kubernetes-el.

Projects: Add kubernetes-el (Emacs client)

---

docs/projects/projects.md

Aptakube is a fresh take on viewing Kubernetes resources from your desktop, allowing teams to view multiple clusters simultaneously, as if it was just one big cluster.

add Aptakube

---

docs/articles/articles.md

The blog moved, so two links listed here were outdated (they lead to the Medium articles, which don't have full content).

Updating links for the Flant blog

---

docs/managed-kubernetes/managed-kubernetes.md

This adds [Avisi Cloud](https://avisi.cloud/kubernetes) to the managed kubernetes list. Avisi Cloud is a [CNCF member](https://landscape.cncf.io/?selected=avisi-kcsp) and provides a managed Kubernetes platform and it's own Kubernetes distribution for multi-cloud for the enterprise.

Add Avisi Cloud to managed Kubernetes list

---

docs/projects/projects.md

Simplyblock is not an open source project, hence it would apply to the exception. Simplyblock is a disaggregated, cloud-native storage solution, designed for Kubernetes CSI and NVMe technology from ground up and simplyblock as a company is a CNCF member. I'd appreciate if you could accept the listing.
----
As a part of our practice, we would like to select the projects based on the below criteria. Please ensure that your submission is fulfilling the below requirements.
- Project is hosted by a recognized organization ✅

Added simplyblock to projects

---

docs/README.md
docs/learning-resources/interactive-environments.md

I work at LabEx, a unique learning platform that has delivered thousands of linux and devops hands-on labs over the past 7 years. This series of free kubernetes tutorials is designed based on our Hands-on Labs. You can read them without logging in, and all labs can be run on your local machine, making them perfect for beginners.
This repo is a great resource. Please let me know if any changes are needed.

Add Kubernetes hand-on labs to Interactive Learning Environments section

---

docs/projects/projects.md

PR - Updated projects.md to include loxilb project
