README.md
Add Datadog as a Kubernetes monitoring tool.
=> add datadog as a kubernetes monitoring tool

README.md
That book is definitely the best seller about docker and kubernetes in China
=> Propose a best seller book about k8s in China

README.md
=> Update Using Weave with Kubernetes..

README.md
I think this should go into a sub-section maybe for things that are purely for building/deploying to your own Kubernetes cluster, while still being Kubernetes.
Since I don't know if [Noel](https://github.com/ramitsurana/awesome-kubernetes/pull/9) should go in this section too.
=> Add spread build/deploy tool

README.md
Reverts ramitsurana/awesome-kubernetes#13
=> Revert "adding history"

.travis.yml, README.md
Fixing a couple of minor spelling issues.
=> Fix minor spelling error, add Reddit as a Resource, and fix travis CI checks

README.md
"The Children's Illustrated Guide to Kubernetes" is awesome.
=> added new link to starting points section

README.md
Signed-off-by: Peng Xiao <xiaoquwl@gmail.com>
=> add kubernetes bootcamp

README.md
Connect to kubernetes services running in your cluster directly through a VPN. Also allows you to easily route kubernetes services back to applications running on a VPN client.
=> Adds kube-openvpn

README.md
it has a different website from sysdig open source tool
=> added sysdig commercial monitoring product

README.md
Adding a couple of Packt books that were missing. I *think* the list of books is now exhaustive!
=> Adding Ebooks

README.md
With a lot of options out there, thought it would be nice to have a list of them. These are a few I know of, in no particular order.
=> A section for kubernetes installers

README.md
There's Vitess already two lines below deleted line
=> Delete Vitess duplicate line

README.md
This Lab Handbook is on updating.
Signed-off-by: Peng Xiao <xiaoquwl@gmail.com>
=> add Docker Kubernetes Lab Handbook

README.md
=> Fix link to API/CLI adaptors

README.md
Added a section for Kubernetes operators with some examples.
=> Added operators section

README.md
Kube-router is all in one distributed load balancer, firewall and router for Kubernetes. Its in WIP solution.
=> Adding Kube-router to networking section.

README.md
Add:
- Networking: https://www.cilium.io/
- Continuous Delivery: https://github.com/GoogleCloudPlatform/continuous-deployment-on-kubernetes
=> Add new links: Networking and ContinuousDelivery

README.md
This PR add KubeNow in the installers
=> Add KubeNow

README.md
Add various operators to the list.
=> Update Operators & Addition of Developer Libraries

README.md
[kubesec](https://github.com/shyiko/kubesec) - Secure Secret management for Kubernetes
=> Add kubesec

README.md
new a Persistent Volume Provider
=> Adding portworx

README.md
(my editor also deleted some extra whitespace)
Telepresence lets you debug/develop services locally while proxying to your remote Kubernetes cluster.
=> add Telepresence

README.md
See #85.
Feel free to move the link to another section.
No stress if the site is not of interest in the first place.
=> Add containers-weekly.com

README.md
Hi, thanks for this awesome list of awesome things :)
This is a brilliant case of study about installation of Kubernetes from scratch on Google Cloud.
Can be usefull for bare metal, vm, etc ... and not only GCloud.
=> Add kubernetes-the-hard-way

README.md
Adds the important section on robustness testing to assert the resilience of applications running on Kubernetes.
=> Add section on robustness testing.

README.md
This PR adds CircleCI to the section on Continuous Delivery.
=> Add CircleCI to Continuous Delivery.

README.md
Adds FaaS-netes to the section on Serverless Implementations.
=> Add FaaS-netes to Serverless Implementations.

README.md
Hi @ramitsurana just seen this list, very neat!
Here is my link change.
=> Updating name of project FaaS -> OpenFaaS

README.md
Hi,
I submit my small installer and a blog post I wrote !
Thanks you for this awesome ressource.
=> Add Simplekube installer & blog post

README.md
It should be _OpenShift in Action_ rather than _Openstack in Action_.
=> Fix title of OpenShift in Action

README.md
add a Persistent Volume Provider
=> add openebs

README.md
Rook is an open-source cloud/kubernetes native service for file, block and object storage.
=> Add Rook to persistent volume providers list

README.md
The commit added a few CRI engine.
=> Add a few cri

README.md
Fix #109 
Also brought the interactive learning environment and tutorials at top order of menu to bring visibility.
=> Added free courses and tutorials initial list

README.md
Signed-off-by: Junaid Ali <junaidali.yahya@gmail.com>
=> Add conjure-up to list of Kubernetes installers

README.md
=> Fix Ubernetes proposal link

CONTRIBUTING.md, Makefile
Fix #112  Developer can now able to test the links locally.
My run
```
$ gem list | grep awesome_bot
$ echo $?
1
$ make test
which: no awesome_bot in (/home/budhram/.linuxbrew/bin:/home/budhram/.rvm/gems/ruby-2.4.1/bin:/home/budhram/.rvm/gems/ruby-2.4.1@global/bin:/home/budhram/.rvm/rubies/ruby-2.4.1/bin:/home/budhram/redhat/ubuntu_vm/google-cloud-sdk/bin:/home/budhram/Gogland-171.4424.55/bin:/home/budhram/go/bin:/home/budhram/gowork/bin:/home/budhram/.linuxbrew/bin:/home/budhram/redhat/ubuntu_vm/google-cloud-sdk/bin:/home/budhram/Gogland-171.4424.55/bin:/home/budhram/go/bin:/home/budhram/gowork/bin:/usr/lib64/qt-3.3/bin:/usr/lib64/ccache:/home/budhram/go/bin:/home/budhram/gowork/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/home/budhram/.rvm/bin:/home/budhram/.rvm/bin:/home/budhr …
```
=> Add mechanism to test links at dev machine

README.md
Fission Workflows is a workflow-based serverless function composition framework built on top of Kubernetes.
=> Add Fission Workflows to related projects

README.md
Add link official vault kubernetes support recently announced by hashicorp
=> Add vault auth plugin backend: kubernetes

README.md
* kube-ansible: Build a Kubernetes and Ceph cluster using Ansible playbooks.
* play-with-k8s: Free Kubernetes playground.
=> Add kube-ansible and play-with-k8s

README.md
https://kubesec.io/ is static analysis for YAML: it catches security errors and suggests enhacements
=> Add kubesec.io

README.md
This PR adds a link to my k8s-testsuite Github project. For details please see Readme of the project.
=> Added link to k8s-testsuite

README.md
This article help user to choose a CNI provider.
=> Add good articles for CNI

README.md
Add Kubermatic to:
- Managed Kubernetes
- Enterprise Kubernetes Products
=> Add Kubermatic to Managed Kubernetes

README.md
- alphabetized the list because FIFO would be awkward here
=> Initial implementation for #134

README.md
The PostgreSQL Operator will also be highlighed on Kubecon: https://kccncna17.sched.com/event/CU7G/kube-native-postgres-i-josh-berkus-redhat
=> add Zalando's PostgreSQL Operator

README.md
Adding Canonical Distribution of Kubernetes and Rancher
=> CDK from Canonical and Rancher

README.md
Following up from https://github.com/ramitsurana/awesome-kubernetes/pull/144
=> Suggest Powerfulseal Kubecon 2017 Austin video

README.md
=> Please add few ressources (Saltstack, IPv6 blog posts..)

README.md
Add a new section for ML, this section includes ML tool, deployment for Kubernetes.
=> Add a new section for ML

README.md
I'm open to questions and conversations on Twitter :)
=> idvoretskyi listed

README.md
This will add HAProxy Ingress as an option of load balancer
=> Add HAProxy Ingress load balancer

README.md
#134 
Signed-off-by: Amit Kumar Jaiswal <amitkumarj441@gmail.com>
=> Added Amazing K8s people!

README.md
Removed one 404ed article and added two new articles on setting up k8s on rasbpi
=> New resources for Raspberry Pi

README.md
Added into the Books section:
"The DevOps 2.3 Toolkit: Kubernetes" by Viktor Farcic
=> Added Book "The DevOps 2.3 Toolkit: Kubernetes"

README.md
=> Remove obsolete "Amalgam8" which is now merged into Istio

README.md
https://apacheignite.readme.io/docs/kubernetes-deployment
=> Add Apache Ignite Kubernetes installation to Databases list

README.md
[kubensx](https://github.com/shyiko/kubensx) - Simpler Cluster/User/Namespace switching for Kubernetes
(featuring interactive mode and wildcard/fuzzy matching (among other things)).
(demo - https://asciinema.org/a/wtn1L6Tq4wavQcKbIn45lDiLe)
=> Add kubensx

Dockerfile
Use `#` instead of `//` for comments :)
=> Fixed Docker build

README.md
Added my series, Kubernetes and everything else, where we take an evolutionary approach showing how things have been and what kubernetes fixes along the way we get introduced to App Development, Containers and in Kubernetes Pods, Services and Deployments.
=> added another article

README.md
Add Amsterdam, Munich & Hamburg MeetUp
=> Add MeetUps

README.md
add the ContainerDays to the conference list
=> Add Conference

README.md
Add `kubeci` to the ci/cd list
=> Add CI tool

README.md
Next try to get "docker build: passing" displayed 😉
=> Fixed Docker build shield

README.md
https://hackr.io/tutorials/learn-kubernetes
=> Added Community Curated Kubernetes Resources

README.md
=> Added Hasura to PaaS

README.md
@idvoretskyi Thanks for merging the pull request. Since Hasura provides the git push workflow over Kubernetes with configuration to manage the cluster, it's best if Hasura is classified as PaaS as well. PR for the same. Thanks in advance! :)
=> Updated Hasura category

README.md
Added k8s-rds to the database section
=> Added k8s-rds to databases

README.md
Rancher Kubernetes Engine, an extremely simple, lightning fast Kubernetes installer that works everywhere.
=> Add Rancher RKE Kubernetes Installer

README.md
Azure Container Service (AKS) manages your hosted Kubernetes environment, making it quick and easy to deploy and manage containerized applications without container orchestration expertise. It also eliminates the burden of ongoing operations and maintenance by provisioning, upgrading, and scaling resources on demand, without taking your applications offline.
Azure AKS works in Azure Public cloud, but is not available in Azure Private Clouds.
=> Add Azure Container Service AKS

README.md
Ark is a utility to backup and restore Kubernetes cluster resources and persistent volumes.
* Take backups of your cluster and restore in case of loss.
* Copy cluster resources across cloud providers.
* Replicate a production environment for development and testing environments.
=> Add Disaster Recovery/Backup and Restore Tool: Ark

README.md
[Kubernetes Comic](https://cloud.google.com/kubernetes-engine/kubernetes-comic/) is an awesome and small comic that explains why should one use k8s(and also containers). 
Though it is followed by a sales pitch.
=> Kubernetes Comic added

README.md
Heptio Sonobuoy is a diagnostic tool that makes it easier to understand the state of a Kubernetes cluster by running a set of Kubernetes conformance tests in an accessible and non-destructive manner. It is a customizable, extendable, and cluster-agnostic way to generate clear, informative reports about your cluster.
=> Add Sonobuoy Heptio tool

README.md
Add one Packt book last year, and one updated coming soon
=> add Packt new books

README.md
Teresa is an extremely simple platform as a service that runs on top of Kubernetes. It uses a client-server model: the client sends high level commands (create application, deploy, etc.) to the server, which translates them to the Kubernetes API.
=> Add teresa

README.md
adding Typhoon installer
https://typhoon.psdn.io/
=> adding Typhoon installer

README.md
Draft is a tool for developers to create cloud-native applications on Kubernetes
=> Add Draft to README.md

README.md
Port of kube-ps1 to the tmux status line.
=> Kubernetes tmux plugin to display the current context and namespace.

README.md
Note - there were issues with some links when I ran `make test`, but none of them were the link that I am adding. I added an issue for the broken links in #239 - I would be happy to help with fixing them if needed.
=> Add Conjur to Secret generation and management

.travis.yml
CI is erroring out on the space character
=> Add img.shields.io to whitelist

README.md
- Alphabetize meetup list
- Add Boston meetup group (cc @mikesplain, @rettori)
- Fix spelling of San Francisco
Great repo you have here - thanks!
=> Clean up meetup list, add Boston meetup

README.md
=> Add the Pittsburgh Kubernetes Meetup group

README.md
Add certified by Splunk applications for monitoring Kubernetes, OpenShift and Docker in Splunk Enterprise and Splunk Cloud.
=> Outcold Solutions Monitoring

README.md
Adding Codefresh to Kubernetes Continuous Delivery
=> adding Codefresh to Kubernetes CI/CD

.travis.yml, README.md
Alauda ee is paas platform built on Kubernetes  which focused on devops, microservice management and ML.
=> Add alauda.io to Paas platform list

README.md
* Removed some old stuff
* Fix broken links
=> fix pipeline and prune old stuff

README.md
The project has matured considerably since #247. Hope we can get this added to this awesome list.
=> Add MetalK8s to installers

README.md
avi networks added to the load balancer list
=> avi networks added

README.md
Yeah I don't know what my workstation just did with the last PR sorry.
=> Add Instana to monitoring services

README.md
=> adding magic sandbox

README.md
Hi there!
I thought this book about Docker might be good match for updating you book list.
Thank you for your consideration,
Rada.
=> adding to your book list

README.md
This pull requests adds the DevSpace CLI to the README.md
=> Add DevSpace

README.md
[Kubespy](https://github.com/pulumi/kubespy) makes it easy to observe changes to Kubernetes resources in real-time. I've found it extremely useful in day-to-day development, as well as for debugging.
=> Add pulumi/kubespy.

README.md
Add [kube-hunter](https://github.com/aquasecurity/kube-hunter) tool under Security
=> Add kube-hunter security tool

README.md
[Kubernetes Security Best Practices](https://dev.to/petermbenjamin/kubernetes-security-best-practices-hlk)
=> Add Kubernetes Security Best Practices article

README.md
=> Add Oracle Kubernetes Engine

README.md
Add kubecfg. Description inline.
=> Add kubecfg

README.md
And make the last letter of `systemd` lowercase.
=> Add changelog for 1.13

README.md
I am the author of the book "[Playing with Java Microservices on Kubernetes and OpenShift](https://leanpub.com/playing-with-java-microservices-on-k8s-and-ocp)" that I recently published on Leanpub. The book is covering Java Microservices architecture and how to deal mainly with Kubernetes and OpenShift.
=> Adding my Kubernetes book to list

README.md
They are a different way for Kubernetes to attach storage and therefore it makes sense to have an own section.
=> Add section Container Storage Interface Plugins

README.md
A simple kubernetes HA installer
=> Add sealos

README.md
Add some classic storage vendors, they are providing Kubernetes plugins.
=> Add classic storage vendors plugins

README.md
The CNCF Cloud Native Landscape Project does give a good overview about a lot of Kubernetes related projects.
=> Add Cloud Native Landscape

README.md
I'm adding Jenkins Operator to the list.
https://github.com/VirtusLab/jenkins-operator
=> Add virtuslab jenkins-operator

README.md
More info: https://newrelic.com/platform/kubernetes and https://blog.newrelic.com/product-news/kubernetes-cluster-explorer
=> Add New Relic as monitoring service

README.md
add a link to a video demo of automating CI/CD on kubernetes using the Jenkins X OSS project which has > 2k stars and 92 contributors: https://github.com/jenkins-x/jx
=> added CI/CD demo with Jenkins X

README.md
(Have made requested changes)
Thank You for creating a Pull Request. We appreciate your efforts towards contributing the awesome-kuberntes list.
=> Added Calico Network Policy and Tigera Secure to Security section

README.md
Thank You for creating a Pull Request. We appreciate your efforts towards contributing the awesome-kuberntes list.
=> Add Linode installer, CSI and CCM (Load balancing)

README.md
Hello! Hopefully these are useful contributions to this list. Please let me know if I can provide more documentation or context around any of these items.
=> Add blog article, and KubeSail PaaS

PULL_REQUEST_TEMPLATE.md
Small spelling error in PR template
=> [PULL_REQUEST_TEMPLATE] fix spelling mistake

README.md
=> Add Kubernetes and Cloud Native Tunisia meetup group

README.md
Add of the new service by OVH about Kubernetes on their public cloud offer.
=> Add OVH Managed Kubernetes to Managed Kubernetes

README.md
Hi, 
Added Docker in Practice 2nd Ed. to the book list for your consideration.
Thank you,
Marko
=> Added Docker in Practice 2nd Ed. to Book List

README.md
=> Add the operator kured

README.md
Link added to Articles / CI/CD category.
=> Article: CI/CD for Microservices on DO K8s

README.md
[Pulumi project repo](https://github.com/pulumi/pulumi)
=> Add Pulumi for configuration

README.md
=> Added Learnk8s Twitter account

README.md
Heptio has renamed Ark to Velero.
=> Rename Heptio Ark to Velero

README.md
=> Add NexClipper for monitoring

README.md
For reference: https://landscape.cncf.io/headquarters=stockholm-sweden&organization=elastx&project=member
=> Added ELASTX as a managed Kubernetes provider

README.md
* [shipper](https://github.com/bookingcom/shipper) Customizable multi-cluster rollouts for Kubernetes
=> adding shipper to cicd tools

README.md
=> update envoy link

README.md
=> Added reference to kail

README.md
https://github.com/mhausenblas/kboom
=> Adds kboom

README.md
Per your request: https://kubernetes.slack.com/archives/C95FG8N3S/p1555562995008300
=> Imperative vs. Declarative — a Kubernetes Tutorial

README.md
added https://github.com/kubernetes-sigs/krew/
=> add plugins manager

README.md
- Added Reloader, Forecastle and Git Webhook Proxy
- Moved Ingress Monitor Controller
=> Add Reloader, Forecastle and Git Webhook Proxy

README.md
Provided by Red Hat and Microsoft
=> Add KEDA Kubernetes-based Event Driven Autoscaling

README.md
Breeze is an open source trusted solution allow you to create Kubernetes clusters on your internal, secure, cloud network with graphical user interface.
=> Add installer Breeze

README.md
Sharing an open source book on Kubernetes focused on deployment learnings as well as a security tool called kube-score
=> Adding open source book + kube-score to tools section

README.md
=> add KubeInvaders

README.md
Markdown link was not correctly formatted
=> Fix hyperlink in `Getting Started` section

README.md
=> Add Kata Containers

README.md
I'm the author of "Continuous Integration and Delivery to AWS Kubernetes", an in-depth tutorial on deploying a microservice app to AWS Kubernetes (EKS) using Semaphore. I'm submitting the link for your consideration, next to the other Semaphore blog posts. 
Thank you
Tomas.
=> CI/CD AWS Kubernetes on Semaphore

README.md
Adding Yggdrasil Envoy Control Plane for Kubernetes Multi-cluster Ingress
=> Added Yggdrasil

README.md
This is a simple spelling fix, nothing added to the overall list.
=> spelling fix for dashboard

README.md
Add Changelog for Kubernetes 1.15 and great project kube-state-metrics
=> add kubernetes 1.15 and kube-state-metrics

README.md
Our team launched today an open source Kubernetes app for managing port forwarding. We made a nice UI and a few interesting features that make using Kubernetes simpler. 
Check out the website https://kube-forwarder.pixelpoint.io/ 
I think the app deserves to be on that list.
=> Added Kube Fordwarder desktop app

README.md
- Add **Nirmata: Enterprise-Wide Kubernetes Management Solutions** under Managed Kubernetes
=> add nirmata

README.md
This PR adds several utilities that we have been testing and using in production for a long time.
=> Add more usefull tools

README.md
Forma is the first in the world real Multi-cloud Remote Blockchain Infrastructure Orchestrator with Kubernetes. Developers can use it and deploy in just 3 clicks also with APIS to create decentralized apps. Focus in enterprise blockchain with startups and enterprise companies deploying easily through Kubernetes.
=> Very popular Enterprise Blockchain Orchestrator

README.md
- Create new sub-section for 'Policy Management' or suggest a section for the project.
- Add Kyverno to the above 'Policy Management'
**Kyverno** - Kubernetes Native Policy Management
=> add kyverno under policy management

README.md
Add link to https://github.com/autoapply/autoapply
=> Add link to autoapply

README.md
=> add new category debug and new projects

README.md
=> Add Tilt to README.md

README.md
k9s is an awesome cli tool to visualize all the objects within your cluster.
=> Adding k9s

README.md
Add [kube-ladder](https://github.com/caicloud/kube-ladder) to Tutorials.
Published by [Caicloud](https://intl.caicloud.io/).
Written in Chinese.
Aim to be a great tutorial to learn k8s.
=> docs(*): add tutorial kube-ladder

README.md
k8s_raw has beed deprecated, update link to k8s module.
=> Update Ansible link

README.md
KubeSphere provides users with easy-to-use interface and wizard design, it reduces the complexity of development, testing and maintenance, as well as lower the learning cost of the container orchestration platform.
Homepage: https://kubesphere.io/en
Github Repo: https://github.com/kubesphere/kubesphere  650 stars, 18 contributors
=> add KubeSphere link

README.md
Kubectl plugin to view cluster resource utilization.
=> Added kubectl plugin view-utilization

README.md
Add a set of tool to help deploy applications with ERB templating, ejson and other nice tools
=> Introduce kubernetes-deploy

README.md
=> add tubectl to adaptors

README.md
=> Add vmware octant to web applications

README.md
Signed-off-by: Gergely Imreh <imrehg@gmail.com>
=> Add changelog for Kubernetes 1.16

README.md
=> Add tutorial for researcher

README.md
=> Add Maesh to Service mesh section.

README.md
=> Add Kuma to Service mesh section.

README.md
=> Added CKAD to Certifications

README.md
=> Add Submariner to Networking section.

README.md
Google+ is gone and shut down - removed link to dead resource.
=> Deleted dead link to G+

README.md
=> Add RancherOS to Operating System section.

README.md
=> Articles/Others: Kubernetes Deployments guide

README.md
=> Add Kontena Lens to web applications section.

README.md
=> Add webkubectl

README.md
Add Kyma to the list of PaaS solutions
=> Add Kyma to the list

README.md
I recently put together a Kubernetes cluster on Raspberry Pi and wrote up an easy to follow tutorial article. I think this article will be useful to the Kubernetes community since it is more up-to-date than the other articles on the list.
=> Add up-to-date article to Raspberry Pi section

README.md
Set static ip for nodes on GKE (useful for whitelisting ips)
=> Add kubeip

README.md
Hi,
I am Branko and I work for Manning Publications. I thought this new edition of Learn Azure in a Month of Lunches might be a good resource for your list.
Thanks for considering it!
=> Added Learn Azure in a Month of Lunches, Second Edition

README.md
=> update introduction for KubeSphere, add Porter to LB item

README.md
---
Adds Atlassian Escalator autoscaler for large production batch/job workload horizontal autoscaling
=> Add escalator autoscaler

README.md
Added predator to k8s testing. 
Link to it's documentation: https://zooz.github.io/predator/about.html
=> Add predator to k8s testing

README.md
=> Add descriptions to projects

README.md
=> Added ktunnel

README.md
=> Change Heptio references to VMware

README.md
There are many high quality plugins there, it might be better to delegate this instead of adding all plugins here.
Was also recognized by maintainers of the official plugin manager (krew) https://github.com/ishantanu/awesome-kubectl-plugins/issues/4.
=> Add awesome kubectl plugins

README.md
Ramit, 
Would appreciate if you would consider adding a link to the free course authored by me at School of Devops. For reference, I am a EDX author (https://www.edx.org/course/introduction-to-site-reliability-engineering-and-devops), book author, have 29k+ students on Udemy and a devops corporate trainer.  
Cheers
Gourav
=> adding a free course on Kubernetes by School of Devops

README.md
Cluster APIs are becomming more and more relevant and should be
mentioned in the list.
=> Add Cluster API Providers

README.md
=> add Dynatrace Kubernetes monitoring

README.md
A Chaos Engineering Platform for Kubernetes
=> Added chaos-mesh

README.md
Hey hey, 
I'm submitting [Netdata](https://www.netdata.cloud/) for the awesome-Kubernetes list. Netdata is an open-source Kubernetes monitoring and visualization service. The [project](https://github.com/netdata/netdata) has 44.8k GitHub stars and 300+ contributors. More information on the project and goals can be found [here](https://blog.netdata.cloud/posts/redefining-monitoring-netdata/). Thank you!
- Proper documentation of the project and its …
=> Add Netdata Kubernetes monitoring

README.md
=> Added Kubevious to Web Applications

README.md
Project: https://github.com/yugabyte/yugabyte-db
3.6K stars
86 contributors
YugabyteDB is a high-performance, cloud-native distributed SQL database
For more documentation, refer to the github project README.
=> added yugabytedb

README.md
=> StatusBay - Deployment visiblity

README.md
All submission criteria seem to be met.
=> add kui to cli listing

README.md
=> Kontena Lens is a desktop App.

README.md
=> Sysdig.org is for sale

README.md
=> add benchmark tools

README.md
Add useful posts to a deep understanding of Kubernetes load balancing.
=> Add load balancing posts

README.md
The goal of this PR is to add the Kubernetes 1.18 release notes to the README.md
=> Update Kubernetes-1.18 Release Notes

README.md
A usefull approach of monitoring, directly coupled with financial impact.
=> Add Kubecost

README.md
=> Deprecate RPC > Micro entry

README.md
We just launched our platform beta for community use today: https://github.com/pixie-labs/pixie. You can learn more about us here: https://docsend.com/view/kj38d76.
It'd be great to get share with community.
=> Add Pixie to related software list

README.md
=> add links to readme about CiCD

README.md
https://github.com/ramitsurana/awesome-kubernetes/issues/528#issuecomment-567799582
=> Add Stash Backup tool

README.md
=> Add podcasts section and the Kubernetes Podcast

README.md
=> Update JJ info

README.md
=> Add KUDO and KUTTL

README.md
=> add electro monkeys podcast

README.md
=> Add Cloud Foundry to the PaaS list

README.md
=> add kubectl-neat

README.md
=> Add replex.io

README.md
=> add Couchbase to database section

README.md
Thanks a lot for this awesome list!
I'd like add this article to the Raspberry Pi section: https://ttt.io/anatomy-of-my-kubernetes-cluster.
It's been originally posted on HN: https://news.ycombinator.com/item?id=22617684.
=> Add 'Anatomy of my Kubernetes Cluster' article to Raspberry Pi section

README.md
=> Added 2 Guides and a link to Sematext under Monitoring Services

README.md
- Added TiDB Operator to the `Operators` list
- Added TiDB to the `Database` list
- Added a new list for chaos engineering on kubernetes
=> Add an operator and a new list for chaos engineering

README.md
=> Add Konvoy, Kommander and Dispatch

README.md
The project has been discontinued.
=> Remove Supergiant

README.md
We are not open source and thus do not have stars and contributors. Are there any other criteria to be listed?
=> Added Humanitec

README.md
Microconfig is open source and build to manage all types of microservice configuration. Works great with Kubernetes.
- Minimum of 25 GitHub Stars ✅ 
- Minimum of 3+ contributors ✅ 
- Proper documentation of the project and its goals ✅ 
=> Add Microconfig

README.md
=> provide direct link so that you don't need to put in your mail address

README.md
=> Add Kubie to API/CLI adaptors

README.md
=> add pluto cli tool

docs/managed-kubernetes/managed-kubernetes.md
=> Adding kore, kubernetes for teams

docs/projects/projects.md
The list of CSI drivers supported by OpenEBS are:
- https://github.com/openebs/cstor-csi
- https://github.com/openebs/zfs-localpv
- https://github.com/openebs/Mayastor
=> add openebs to projects supporting CSI drivers

docs/articles/articles.md
=> add Kubernetes Operators Explained

docs/installers/installers.md
Suggesting [KubeOne](https://www.kubermatic.com/products/kubeone/) which is pretty good for single clusters. Supports multiple cloud providers. Tested with Hetzner and works great.
=> Suggesting KubeOne

docs/articles/articles.md
=> Adding a few K8s articles written by Flant

docs/articles/articles.md
=> Adding Kubernetes articles on medium

docs/installers/installers.md, docs/managed-kubernetes/managed-kubernetes.md
* Add Spectro Cloud
* CNCF member: https://landscape.cncf.io/selected=spectro-cloud
=> Add Spectro Cloud

docs/README.md
This 15,000+ words article is divided into 33 sections and walks readers through all the fundamentals of Kubernetes with project examples hosted in the [fhsinchy/kubernetes-handbook-projects](https://github.com/fhsinchy/kubernetes-handbook-projects) repository.
=> Added 'The Kubernetes Handbook'

docs/projects/projects.md
- 221 stars
- 5 authors
- Proper documentation of the project and its goals - yes
Thanks for you awesome work !
=> add kubepug in testing projects

docs/projects/projects.md
=> add kubeedge project in related software

docs/projects/projects.md
This is a personal project that we use in production, fits the pull request requirements.
Hope this help.
Thanks !
=> add untrak project in configuration section

docs/projects/projects.md
=> add cilium project in service mesh section

docs/projects/projects.md
=> Add pipecd to projects

docs/learning-resources/books.md
Signed-off-by: Armin <armin@coralic.nl>
=> Adding Container platform for the Enterprise book

docs/projects/projects.md
All my OSS projects now moved from GitHub to https://codeberg.org/hjacobs
=> kube-ops-view and kube-resource-report moved to codeberg.org

docs/learning-resources/certifications.md
- Add CKA resources repo 2.4k stars
- Add CKS resources repo
=> Add CKA and CKS resources

docs/README.md, docs/projects/projects.md
* Add https://www.k8gb.io/ to Load Balancing projects (40 stars, 4 contributors)
* Inline broken CONTRIBUTING link fix in README
=> Add k8gb - Kubernetes Global Balancer

docs/README.md
=> Added my book Bootstrapping Microservices to the list.

docs/README.md
Hi,
Branko from Manning Publications here, I thought this book of ours would be a good resource for the list.
Thanks for considering it!
=> added Kubernetes Native Microservices with Quarkus, and MicroProfile

docs/projects/projects.md
=> add k8s-image-swapper to related software

docs/managed-kubernetes/managed-kubernetes.md
Adding Flant & Giantswarm, updating links for OpenShift Online and ELASTX.
=> Managed K8s providers updates

docs/managed-kubernetes/managed-kubernetes.md
Update of existing entry. Thanks.
=> Update slogan for Humanitec

docs/articles/articles.md
Add _Attacking Kubernetes clusters using the Kubelet API_ article.
=> Add Security Article

docs/README.md, docs/learning-resources/slides.md
Please add my slide on "Kubernetes Pod internals with the fundamentals of Containers".
This slide was originally published in Korean. I shared it(Korean version) on Facebook 'Kubernetes Korea Group' a few days ago. This slide received more than 100 Likes and was re-shared more than 100 times to others.
(You can check the post here: https://www.facebook.com/groups/k8skr/permalink/2982791885335798/)
I have translated and reviewed it in English with @juneoh, and I hope this can be posted on awesome-kubernetes project for those who are learning Kubernetes.
---
Thank You for creating a Pull Request. We appreciate your efforts towards contributing the `awesome-kubernetes` list.
As a part of our practice, we would like to select the projects based on the below criteria. Please ensure that your …
=> Add slide on "Kubernetes Pod internals with the fundamentals of Containers"

docs/README.md
Hi 👋🏻 Great project! Just swapping this line out for gender-neutral language. Hope that's all right 👍🏻
=> Replace 'guys' with 'everyone'

docs/applications/applications.md
=> Update applications.md - Add click-to-deploy samples repo

docs/projects/projects.md
Signed-off-by: Pavel Malinov <pmmalinov01@gmail.com>
=> Adding useful tool to check deprecated API if they are used.

docs/projects/projects.md
Hi 👋 
A little PR to fix the Sysdig secure link 🔗 
Have a nice day!
=> Fix Sysdig secure link

docs/projects/projects.md
=> YAML/JSON Config - update description of resources

docs/README.md
Added a blog related to deploy REST API in Kubernetes
=> Added a blog related to deploy REST API in Kubernetes

docs/installers/installers.md
=> Fix link for Canonical Kubernetes

docs/articles/articles.md
Fix 404 link to Twitter. See #685 .
=> Fix deadlink of Coreos Twitter

docs/projects/projects.md
=> Add JuiceFS to projects

docs/projects/projects.md
Anchore Engine is an open-source project that provides a centralized service for inspection, analysis, and certification of container images. https://github.com/anchore/anchore-engine
=> Added Anchore Engine

docs/installers/installers.md
=> Add k0s to list of installers

docs/projects/projects.md
Hi!
This PR adds DETIK in the list of testing resources.
About the requirements:
- Minimum of 25 GitHub Stars => DETIK currently has 74 stars
- Minimum of 3+ contributors => 5 contributors at the moment
- Proper documentation of the project and its goals => in the README file
=> Add DETIK in the list

docs/README.md
Hi,
Stjepan from Manning here. I thought this title might be a good match to your list. Thank you for considering it.
Best,
=> Added Securing Kubernetes Secrets

docs/projects/projects.md
**About the Project:** 
Configurator is a version control and sync service that keeps Kubernetes ConfigMaps and Secrets in sync with the deployment. Configurator uses CRDs to create CustomConfigMaps and Customrets that in turn create ConfigMaps and Secrets with a postfix. As and when a change is detected in the CustomConfigMap or CustomSecret, Configurator automatically generates a new ConfigMap with a new postfix. This acts like version control for ConfigMaps.
**What problem does it solve?**
Facilitates ConfigMap rollouts / management
https://github.com/kubernetes/kubernetes/issues/22368
**Does this project fit the criteria?** 
1. stars > 25
2. Contributors > 3
3. It has clear documentation, blogs & a discord server for the community
=> Added configurator to the project list

docs/articles/articles.md
- Project is hosted by a recognized organization.
=> Added article on Kubernetes

docs/managed-kubernetes/managed-kubernetes.md, docs/projects/projects.md
=> Added project Devtron Labs 

docs/projects/projects.md
=> Add Portainer into Related Software, Web Applications, API/CLI adaptors

docs/releases.md
Announcement at https://kubernetes.io/blog/2021/12/07/kubernetes-1-23-release-announcement/.
=> Kubernetes 1.23 released on 2021-12-07

docs/projects/projects.md
=> Add Clusterpedia to Projects

docs/projects/projects.md
=> Add kwatch to Projects

.github/workflows/links.yaml, docs/README.md
I noticed that the workflow for validating links is [creating errors](https://github.com/ramitsurana/awesome-kubernetes/issues?q=is%3Aissue+is%3Aopen+label%3A%22links+validator%22) so this PR fix that.
tested on my fork:
https://github.com/eyarz/awesome-kubernetes-ramitsurana/issues/4
please squash and merge (and not just merge) because I pushed some spammy commits (update readme.md) to test the workflow
=> Fix links validation workflow

docs/learning-resources/books.md
Hi,
I have done as you requested.
Thank you.
Best,
=> Added Google Anthos to the Books section

docs/README.md, docs/articles/articles.md
=> Added ArgoCD best practices article

docs/managed-kubernetes/managed-kubernetes.md
Kubernetes service offering since 2016.
=> Add APPUiO Cloud

docs/projects/projects.md
Adding our terraform-controller project to the list
=> Adding Terraform Controller

docs/projects/projects.md
Speedscale is a YC-backed startup, founded in 2020 and focused on helping teams running workloads on Kubernetes improve their application quality through traffic replay.
=> Adding speedscale to testing list

docs/guidelines/CONTRIBUTING.md
This PR fixes the broken link of CRITERIA_OF_SUBMISSION.md in CONTRIBUTING guide
=> Fix link to CRITERIA_OF_SUBMISSION in CONTRIBUTING.md

docs/managed-kubernetes/managed-kubernetes.md
=> Added gopaddle to the PaaS category

docs/projects/projects.md
=> add Gefyra and Getdeck to project list

docs/extras/social-media.md
* Removed many outdated accounts (not active for years).
* Added categories. Maybe, it should not be "Other" for LearnK8s, but something like "Learning"? It depends on which other links will be there. E.g. if we want to have some "fun" here, we can add [memenetes](https://twitter.com/memenetes) as well. If we want more educational content, [K8sArchitect](https://twitter.com/K8sArchitect) would be a great addition.
* Added a few new accounts.
=> Updating & improving Twitter accounts list

docs/extras/raspberry-pi.md
This article is different from others since it's not limited to installing K8s as it is but also covers installing some essential tools to have a "full-featured" cluster.
=> Adding another Raspberry Pi installation guide

docs/README.md
Remove Kubeflow in Action as it hasn't been published.
=> This book has not been released.

docs/managed-kubernetes/managed-kubernetes.md
[Claudie](https://www.github.com/berops/claudie) creates and operates true multi-cloud clusters. That means clusters which have each nodepool in a different cloud provider. It enables zero-outage workload migration between the cloud providers and frees users from cloud provider lock-in. Developed by [Berops](https://www.berops.com).
=> Add Claudie

docs/installers/installers.md
Added libvirt-k8s-provisioner
https://github.com/kubealex/libvirt-k8s-provisioner
=> Add libvirt-k8s-provisioner

docs/projects/projects.md
=> Adding M9sweeper to list of security projects

docs/projects/projects.md
External Secrets is a CNCF Sandbox project: https://www.cncf.io/projects/external-secrets/
=> Add External Secrets Operator

docs/projects/projects.md
Kairos is an OS designed for running immutable edge Kubernetes. Documentation available at https://kairos.io
Thank you!
=> Add kairos to the project list

docs/projects/projects.md
=> Added kong and emissary ingress in the Load Balancing list

docs/learning-resources/books.md
=> Add Distributed Machine Learning Patterns from Manning

docs/README.md
Hey, I would like to contribute my Kubernetes resource to awesome-kubernetes 🚀
=> Added Resource to README.md

docs/managed-kubernetes/managed-kubernetes.md
This product is no longer being sold.
https://www.cisco.com/c/en/us/products/collateral/cloud-systems-management/intersight/ccp-iks-eol.html
=> Remove Cisco Container Platform

docs/README.md
Fix broken link: Kubernetes-explained medium page
=> Fix README.md broken link

docs/projects/projects.md
=> Add Alaz - Effortless, Low-Overhead, eBPF-based Kubernetes Monitoring

docs/projects/projects.md
[kr8s](https://github.com/kr8s-org/kr8s) is a new Python client library that has spun out of work we are doing on [Dask](https://github.com/dask/dask) at NVIDIA.
=> Add kr8s to Python client libraries

docs/case-studies/case-studies.md
This adds a guideline on how to setup Microservices on Kubernetes.
=> Add case study

docs/projects/projects.md
Add Kyverno Chainsaw in Testing tools.
=> Add Kyverno Chainsaw in Testing tools

docs/projects/projects.md
Cyclops helps developers deploy to K8s by giving them a dynamically rendered UI for their K8s resources
- Minimum of 25 GitHub Stars ✅ 
- Minimum of 3+ contributors ✅ 
- Proper documentation of the project and its goals ✅  (available [here](https://cyclops-ui.com/docs/about/))
=> Add Cyclops UI to `Web applications` projects

docs/README.md
It's a just a fix of outdated link to k8s article. New link is direct link to article on author's Linkedin.
=> fix (link): Update outdated link

docs/projects/projects.md
=> Added K8Studio - a cross-platform client IDE to manage Kubernetes Clusters.

docs/README.md
=> Added Road to Kubernetes

docs/articles/articles.md
=> Add my article: https://semaphoreci.com/blog/kubernetes-rolling-update-deployment

docs/projects/projects.md
=> Add KFtray - cross platform tray app to manage multiples kubectl port forward

docs/README.md
Hi,
Stjepan here from Manning. I thought this title might be a good match for your list. Thank you for considering it.
Best,
=> Added Fluent Bit with Kubernetes

docs/projects/projects.md
Fix multus-cni & stern links in readme
=> Fix multus-cni & stern links in readme

docs/extras/social-media.md
I think adding other social platforms to this page might be beneficial. Thus, I am adding one helpful resource on Telegram as a start.
=> Add Telegram to social-media.md

docs/projects/projects.md
Hi, adding a few open source projects from Robusta.
* [Kubewatch](https://github.com/robusta-dev/kubewatch) is now maintained by Robusta. So the source of the project has been updated to reflect that.
Thanks.
=> Some open source projects

docs/articles/articles.md, docs/projects/projects.md
=> docs/projects/projects.md: adds VictoriaMetrics and VictoriaLogs to the Monitoring Services section

docs/learning-resources/courses.md, docs/learning-resources/interactive-environments.md
[Meshery](https://github.com/meshery/meshery) is a CNCF project and a cloud native manager that enables the design and management of all Kubernetes-based infrastructure and applications (multi-cloud). The hands-on tutorials uses live cluster environment in  Meshery Playground and can be used for exploring all CNCF projects and learning cloud and cloud native technologies. For instance: 
- [Exploring Kubernetes Pods with Meshery](https://docs.meshery.io/guides/tutorials/kubernetes-pods)
-  [x] Minimum of 25 GitHub Stars
-  [x] Minimum of 3+ contributors
-  [x] Proper documentation of the project and its goals
-  [x] Project is hosted by a recognized organization
=> add resources:  hands-on tutorials and meshery playground

docs/projects/projects.md
Add KubeQ to Testing and Troubleshooting section
KubeQ is a fast, simple, and powerful Kubernetes manifest validator that combines kubeval, kube-score, and kubeaudit to provide comprehensive validation of your Kubernetes manifests. No installation required - just paste your manifest and get instant feedback.
This PR adds KubeQ to the Testing and Troubleshooting section of the awesome-kubernetes.
- …
=> Add KubeQ to Testing and Troubleshooting section

docs/learning-resources/courses.md
A free and complete Kubernetes course in French covering core concepts, advanced usage, and practical examples.
=> Add French Course
